import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  documentationSidebar: [{ type: 'autogenerated', dirName: 'documentation'}],
  apiSidebar: [{ type: 'autogenerated', dirName: 'api' }],
  //adminGuideSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
  integrationsSidebar: [{ type: 'autogenerated', dirName: 'integrations'}],
  //lxpSidebar: [{ type: 'autogenerated', dirName: 'lxp'}],
  sdkSidebar: [{ type: 'autogenerated', dirName: 'sdk'}]
};

export default sidebars;