import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  documentationSidebar: [{ type: 'autogenerated', dirName: 'documentation'}],
  apiSidebar: [{ type: 'autogenerated', dirName: 'api' }],
  adminGuideSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
  integrationsSidebar: [{ type: 'autogenerated', dirName: 'integrations'}],
  sdkSidebar: [{ type: 'autogenerated', dirName: 'dk'}]
};

export default sidebars;