import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  documentationSidebar: [{ type: 'autogenerated', dirName: 'Documentation'}],
  apiSidebar: [{ type: 'autogenerated', dirName: 'api' }],
  adminGuideSidebar: [{ type: 'autogenerated', dirName: 'admin-guide' }],
  integrationsSidebar: [{ type: 'autogenerated', dirName: 'Integrations'}],
  sdkSidebar: [{ type: 'autogenerated', dirName: 'Sdk'}]
};

export default sidebars;